# Generated by Django 5.2.16 on 2026-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='statut',
            field=models.CharField(choices=[('a_valider', 'À valider'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='a_valider', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, help_text='Lien externe (vidéo lourde : 0 octet sur le VPS)'),
        ),
    ]
