# Generated by Django 5.2.16 on 2026-09-30 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, help_text='Ex. Imprimerie, Hébergement, Matériel', max_length=100)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('conditions_paiement', models.CharField(blank=True, help_text='Ex. 30 jours, comptant', max_length=255)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('prospect', 'Prospect')], default='actif', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom_societe'],
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=80, unique=True)),
                ('reference_fournisseur', models.CharField(blank=True, help_text='N° facture du fournisseur', max_length=80)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('recue', 'Reçue'), ('validee', 'Validée'), ('payee', 'Payée'), ('partielle', 'Partielle')], default='recue', max_length=20)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, help_text='Scan facture PDF', null=True, upload_to='achats/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneFactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fournisseurs.facturefournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moyen', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte')], default='virement', max_length=20)),
                ('ref_transaction', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='fournisseurs.facturefournisseur')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
