# Generated by Django 5.2.16 on 2026-09-30 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=80, unique=True)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('envoyee', 'Envoyée'), ('partiellement_livree', 'Partiellement livrée'), ('livree', 'Livrée'), ('facturee', 'Facturée'), ('annulee', 'Annulée')], default='brouillon', max_length=25)),
                ('livraison_prevue', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='commande',
            field=models.ForeignKey(blank=True, help_text="Bon de commande d'origine (conversion)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='fournisseurs.boncommande'),
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=80, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=20)),
                ('date_livraison', models.DateField(default=django.utils.timezone.localdate)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='fournisseurs.boncommande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('quantite_livree', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fournisseurs.boncommande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ligne_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='fournisseurs.ligneboncommande')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fournisseurs.bonlivraison')),
            ],
        ),
    ]
