# Generated by Django 5.2.16 on 2026-10-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Siège Digi Com', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rayon_m', models.PositiveIntegerField(default=150, help_text="Distance max (mètres) entre l'employé et l'entreprise.")),
                ('heure_arrivee', models.TimeField(help_text='Début journée (08:00).')),
                ('heure_depart', models.TimeField(help_text='Fin journée (17:00).')),
                ('tolerance_retard_min', models.PositiveIntegerField(default=15, help_text='Retard compté après heure_arrivee + tolérance (08:15).')),
                ('actif', models.BooleanField(default=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actif', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('expire_le', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='rh.employee')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('statut_arrivee', models.CharField(blank=True, choices=[('a_l_heure', "À l'heure"), ('retard', 'En retard')], max_length=10)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('statut_depart', models.CharField(blank=True, choices=[('normal', 'Normal'), ('anticipe', 'Anticipé')], max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='rh.employee')),
            ],
            options={
                'ordering': ['-date', 'employe__user__email'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
