# Generated by Django 5.2.16 on 2026-10-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_sitepointage_qrtoken_pointage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepointage',
            name='prime_montant',
            field=models.PositiveIntegerField(default=25000, help_text="Prime proposée automatiquement à l'employé du mois (F CFA)."),
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(help_text='AAAA-MM', max_length=7)),
                ('montant', models.PositiveIntegerField(help_text='Montant en F CFA.')),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('validee', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='rh.employee')),
            ],
            options={
                'ordering': ['-mois', 'employe__user__email'],
                'unique_together': {('employe', 'mois')},
            },
        ),
    ]
