# Generated by Django 5.2.16 on 2026-09-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(default='Digi Com & Technologies', max_length=255)),
                ('nif', models.CharField(default='081234567A', max_length=50)),
                ('rccm', models.CharField(default='ML-BKO-2021-B-1234', max_length=50)),
                ('adresse', models.CharField(default='Sotuba ACI-2000, Bamako', max_length=255)),
                ('phone', models.CharField(default='(+223) 70 16 33 86', max_length=50)),
                ('email', models.EmailField(default='contact@digicom.ml', max_length=254)),
                ('delai_paiement', models.CharField(default='30 jours', max_length=50)),
                ('signataire', models.CharField(default='La Direction Financière', max_length=100)),
            ],
        ),
    ]
