# Generated by Django 5.2.16 on 2026-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tampons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cachet_secretariat',
            field=models.ImageField(blank=True, null=True, upload_to='cachets/'),
        ),
    ]
