# Generated by Django 5.2.16 on 2026-09-15 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_idx', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('cloturee', 'Clôturée')], default='brouillon', max_length=20)),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='cachets/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-annee', '-mois_idx'],
                'unique_together': {('mois_idx', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='LignePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('departement', models.CharField(default='Administration', max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé')], default='en_attente', max_length=20)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finance.fichepaie')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
