# Generated by Django 5.2.16 on 2026-10-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_est_interne'),
        ('finance', '0005_invoice_tva'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='envoyee_le',
            field=models.DateTimeField(blank=True, help_text='Passage en envoyée (clic WhatsApp ou envoi mail).', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inscription',
            field=models.ForeignKey(blank=True, help_text='Inscription formation facturée (factures formations).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='formations.inscriptionformation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='NULL pour les factures formations (voir inscription).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client'),
        ),
    ]
