# Generated by Django 5.2.16 on 2026-09-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('departments', '0001_initial'),
        ('projects_dev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=254)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_identity', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], default='envoye', max_length=20)),
                ('erreur', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='mailing.emailidentity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects_dev.project')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
