# Generated by Django 5.2.16 on 2026-09-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('secretariat_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariat_tickets.ticket'),
        ),
    ]
