# Generated by Django 5.2.16 on 2026-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='body_html',
            field=models.TextField(help_text="Contenu intérieur uniquement : la mise en page charte (header marine, footer, bouton) est appliquée automatiquement à l'envoi."),
        ),
    ]
