# Generated by Django 5.2.16 on 2026-09-15 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects_dev', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('sens', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant')], default='entrant', max_length=10)),
                ('objet', models.CharField(max_length=255)),
                ('expediteur', models.CharField(blank=True, max_length=255)),
                ('destinataire', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('pv_redaction', 'PV en rédaction'), ('cloturee', 'Clôturée')], default='planifiee', max_length=20)),
                ('ordre_du_jour', models.TextField(blank=True)),
                ('pv', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DecisionReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('echeance', models.DateField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects_dev.task')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='secretariat_tickets.reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('dept_assigne', models.CharField(blank=True, max_length=100)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('qualifie', 'Qualifié'), ('en_attente_aval', "En attente d'aval"), ('approuve', 'Approuvé'), ('repondu', 'Répondu'), ('clos', 'Clos'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects_dev.project')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='TicketApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, choices=[('approuve', 'Approuvé'), ('modifie', 'Modifié'), ('rejete', 'Rejeté')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('reponse_proposee', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avals_demandes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='secretariat_tickets.ticket')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avals_donnes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='secretariat_tickets.ticket')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
    ]
