# Generated by Django 5.2.16 on 2026-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat_tickets', '0002_alter_courrier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('recu', 'Reçu'), ('traite', 'Traité'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
