# Generated by Django 5.2.16 on 2026-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat_tickets', '0003_courrier_contenu_courrier_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='participants',
            field=models.TextField(blank=True, help_text='Noms séparés par des virgules (convocation mail)'),
        ),
    ]
