# Generated by Django 5.2.16 on 2026-09-30 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat_tickets', '0004_reunion_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('provenance', models.CharField(help_text='Qui a remis : personne / service / société', max_length=255)),
                ('objet', models.CharField(help_text='Ce qui est déchargé : montant, documents, matériel…', max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_recue', models.DateField(default=django.utils.timezone.localdate)),
                ('image', models.ImageField(help_text='Scan compressé auto (JPEG 1600px q70)', upload_to='decharges/')),
                ('poids_ko', models.IntegerField(default=0, help_text='Poids après compression (Ko)')),
                ('commentaire', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_recue'],
            },
        ),
    ]
