# Generated by Django 5.2.16 on 2026-10-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_est_interne'),
        ('secretariat_tickets', '0005_decharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSecretariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('offre_technique', 'Offre technique'), ('offre_commerciale', 'Offre commerciale'), ('lettre', 'Lettre'), ('attestation', 'Attestation'), ('note', 'Note de service'), ('autre', 'Autre document')], default='lettre', max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('destinataire', models.CharField(blank=True, max_length=255)),
                ('contenu', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('envoye', 'Envoyé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_secretariat', to='clients.client')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
