# Generated by Django 5.2.16 on 2026-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, help_text="Personnalise l'URL du portail : /espace/<slug>", max_length=255, unique=True),
        ),
    ]
