# Generated by Django 5.2.16 on 2026-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, help_text='Identifiant unique 4 chiffres du portail client', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, help_text="Personnalise l'URL du portail : /espace/<slug>/<code>", max_length=255, unique=True),
        ),
    ]
