# Generated by Django 5.2.16 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_code_alter_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='est_interne',
            field=models.BooleanField(default=False, help_text='Client interne (ex. Digi Com elle-même) : géré dans le hub, sans compte ni espace client (/espace).'),
        ),
    ]
