# Generated by Django 5.2.16 on 2026-10-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Clé stable partagée avec le site vitrine', max_length=200, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('prix', models.PositiveIntegerField(default=0, help_text='Prix en F CFA (XOF)')),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=80, unique=True)),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='recue', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('reference_site', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.participantformation')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
