# Generated by Django 5.2.16 on 2026-09-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('employe', 'Employé')], default='client', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='clients.client')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('clos', 'Clos')], default='ouvert', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges', to='clients.client')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
