# Generated by Django 5.2.16 on 2026-09-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contenu',
            field=models.TextField(blank=True, help_text='Rédaction depuis un modèle'),
        ),
    ]
