# Generated by Django 5.2.16 on 2026-10-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridique', '0004_type_sans_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature_employe_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_employe_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_employe_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
